Append static. Append base.html.
Hovorovskyi/Vector_project pull request #3
Opened 2023-08-01 17:18 UTC by Hovorovskyi

Append meta snd __str__ to models.
Update menu_list.html and try to change login.html
Change settings after removed project in new repo.

2023-08-01 19:01 UTC, vladysllav commented on templates/base.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorig
Скачай бутстрап локально, а не юзай линки

2023-08-01 19:03 UTC, vladysllav commented on user/views.py
> +def home_page(request):
Ты юзаешь эту функцию? Мне кажется нет, ибо она мало смысла имеет, просто возвращает базовый шаблон, он же пустой

2023-08-01 19:03 UTC, vladysllav requested changes
Leave small comments

2023-08-02 12:12 UTC, Hovorovskyi commented on templates/base.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorig
в последнем коммите скачал уже

2023-08-02 12:21 UTC, merged